### ISSUE TITLE
project ing .....

### ISSUE THREAD

**Issue by daewoo1582** [daewoo1582/flyhage#2]
안녕하세요 튜터님~
이벤트 success 가 동작을 하지 않습니다
아무래도 클라이언트에서 주는 변수값을 리스트형을 고려해서 줘야되는 것 같은데...
서버와 클라이언트를 확인을 해도 잘 모르겠습니다 ...

**Comment by hyunsung-kim** [comment]
대우님 templates 아래 파일들이 올라오지 않았습니다.  다시 업로드 부탁드려요

**Comment by daewoo1582** [comment]
선생님~  templates 아래 파일이라고 하면 index.html 파일 말씀하시는 것 아니세요??
전부 다 말씀 하시는건가요??

**Comment by hyunsung-kim** [comment]
templates 아래 전체 올려주시면 됩니다.

**Comment by daewoo1582** [comment]
올라간거같습니다.....

**Comment by hyunsung-kim** [comment]
안올라오네요. 저한테 그냥 파일로 보내주세요.

**Comment by hyunsung-kim** [comment]
올라왔네요. 파일 형식이 틀렸네요

**Comment by daewoo1582** [comment]
전체 이하 끌어다 갖다 놓았는데 머가 잘못된건지....

**Comment by hyunsung-kim** [comment]
원인 찾았고 해결했습니다. 업로드 하려고 하는데 collaborator로 초대 메일을 못찾겠네요

**Comment by hyunsung-kim** [comment]
다시 한번 collaborator 초청해 주세요

**Comment by hyunsung-kim** [comment]
1. 함수로 사용할때는 '[' 대신 '('괄호 사용하셔야 합니다.
```
    list1_receive = request.form.getlist('list1_give[]')
    list2_receive = request.form.getlist('list2_give[]')
    list3_receive = request.form.getlist('list3_give[]')
    list4_receive = request.form.getlist('list4_give[]')
```

2. index.html 파일을 "templates"폴더 아래 두셔야 합니다.

**Comment by hyunsung-kim** [comment]
이거 수정해 주시면 됩니다.

**Comment by daewoo1582** [comment]
다시 초대해 두었습니다 ~~

**Comment by hyunsung-kim** [comment]
감사합니다. 아마 저장 될거 같아요. 다음 페이지 만드시면 됩니다.

**Comment by daewoo1582** [comment]
127.0.0.1 - - [22/Jun/2020 23:27:33] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2020 23:27:34] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [22/Jun/2020 23:28:07] "POST /success HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2020 23:28:11] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2020 23:28:52] "POST /success HTTP/1.1" 200 -
127.0.0.1 - - [22/Jun/2020 23:28:54] "GET / HTTP/1.1" 200 -

디비는 잘 저장되는걸로 확인했고 동작은 잘 됩니다 선생님 위에 저부분은 파이썬 터미널에 찍혀있는데 먼가 오류가 좀 있는걸로 알려주는듯 한데 머죠?

**Comment by hyunsung-kim** [comment]
GET /favicon.ico HTTP/1.1" 404 이건 신경 안쓰셔도 됩니다.

**Comment by daewoo1582** [comment]
html 파일 하나 더 생성해서 하면되죠?

**Comment by hyunsung-kim** [comment]
네 맞습니다 새로운 이슈 생성해 두었습니다. 거기로 이동할게요 ㅎㅎ
