### ISSUE TITLE
[작업] 새로운 페이지

### ISSUE THREAD

**Issue by hyunsung-kim** [daewoo1582/flyhage#3]

**Comment by daewoo1582** [comment]
아 내일 이어서 하고 남기겠습니다~~ 지금 집안 내부문제로 사정상 이어서 하기 힘드네요~
봐주셔서 감사합니다~~!!!

**Comment by hyunsung-kim** [comment]
네 수고하셨습니다.

**Comment by daewoo1582** [comment]
아닙니다 ㅠㅠ 내일은 이슈일찍 남기면서 이어가도록 할게요~~ ㅠㅠ
첫페이지 키워드 리스트 저장되고 ajax로 불러왔을때 석세스 이벤트 동작시 조건문 적용을 잘못한거같아요 제가
키워드 하나만 등록해도 석세스로 잘 저장되었습니다 로 내일 다시 짜야 될 것 같습니다 ㅠㅠ

**Comment by daewoo1582** [comment]
안냐때욥~ 낼 저녁 7시 어디서 진행 하실 예정이십니까???

**Comment by daewoo1582** [comment]
선생님 ~~ 내일 7시에 저는 갈게요~
